"use client";

import { Geist, Geist_Mono } from "next/font/google";
import { usePathname } from "next/navigation";
import "./globals.css";
import { AuthProvider, logout } from "./authContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/
function logoutClicked() {
  logout();
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const showLogout = pathname?.startsWith("/home");
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="min-w-full p-6 flex items-center gap-4">
          <h1 className="text-2xl font-bold self-center mx-auto">
            <a href="/home">To Do Lists</a>
          </h1>
          {showLogout && (
            <button
              className="btnBlue px-4 py-2 rounded"
              onClick={logoutClicked}
            >
              Logout
            </button>
          )}
        </header>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
