-- AlterTable
ALTER TABLE "jobs" ALTER COLUMN "time_created" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "time_created" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "lists" ALTER COLUMN "time_created" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "time_created" SET DATA TYPE TIMESTAMP(3);
